//
//  Client.swift
//  Trile
//
//  Created by Chris Abbod on 12/26/19.
//  Copyright © 2019 Trile. All rights reserved.
//

import Foundation

class Client {
    var name: String = ""
    var documentID: String = ""  //ID given to document generated by firestore database
}
