//
//  FileNumber.swift
//  Trile
//
//  Created by Chris Abbod on 12/31/19.
//  Copyright © 2019 Trile. All rights reserved.
//

import Foundation

class FileNumber {
    var assignedFileNumber: String = ""
    var documentID: String = "" //ID given to document generated by firestore database
}
