# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Trile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trile
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'WeScan', '>= 0.9'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  
  target 'TrileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrileUITests' do
    # Pods for testing
  end

end
