# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trile
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  
  target 'TrileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrileUITests' do
    # Pods for testing
  end

end
